### ISSUE TITLE
[FEATURE]: Increase rate limit for some situations

### ISSUE THREAD

**Issue by SherkeyXD** [helldivers-2/api#106]
### What problem does it solve

For some instances, we need to make requests more than 5req/10s. For example, the current assignment need us to take down 5 planets. And to get full imformation of the progress, we need to make 6 requests at a time (1 assignment + 5 planets)

### What is the solution

Increase it? Or other temporary ways to change limits.

### Existing alternatives

None

### Added value

None

### Additional notes

None

**Comment by TheWizardofGauze** [comment]
Except for extreme cases I don't know that rate limit increases are necessary. Wouldn't it be better to make one request for the assignment and one request for the full planet list and work off that?

That's what I just switched to doing instead and have noticed my program returning results faster at the cost of a few more lines of code.

**Comment by Stonemercy** [comment]
> Except for extreme cases I don't know that rate limit increases are necessary yet. Wouldn't it be better to make one request for the assignment and one request for the full planet list and work off that?
> 
> That's what I just switched to doing instead and have noticed my program returning results faster at the cost of a few more lines of code.

This is what I do, I make a max of 4 or so calls max, normally 1-3, could probably lower the calls I make if I wanted
