### ISSUE TITLE
[FEATURE]: New API Endpoint: Peosonal Order

### ISSUE THREAD

**Issue by SherkeyXD** [helldivers-2/api#107]
### What problem does it solve

To get the personal order.

### What is the solution

Does official API include this?

### Existing alternatives

I know that [helldivers.io](https://helldivers.io/) do have this info, but it's not clear how they made it.

### Added value

The info should include:
+ target
+ prize
+ due

### Additional notes

Translations all also needed.

**Comment by dealloc** [comment]
unfortunately personal orders are tied to the accounts, which requires auth'd endpoints.
This API aims to be 100% open source, and one of the unfortunate side effects is we can't include authenticated endpoints as that would open the door for hackers (I've seen first hand the things you can do with authentication access on the API).

I do think however, @chatterchats might have them in their API?
