### ISSUE TITLE
[FEATURE]: Update Helldivers.Models.V1.Assignment to allow for more than one reward

### ISSUE THREAD

**Issue by raginmari** [helldivers-2/api#109]
### What problem does it solve
Arrowhead's API has an array called "rewards" in their assignment type (on the same level as the known "reward" object) which allows for **more than just one reward** for an assignment.

<img src="https://github.com/user-attachments/assets/5edb1192-7a4f-4742-a1e5-005a92d97907" width="256px" />

```
"rewards": [
    {
        "type": 1,
        "id32": 897894480,
        "amount": 45
    },
    {
        "type": 1,
        "id32": 3608481516,
        "amount": 29000
    }
],
"reward": {
    "type": 1,
    "id32": 897894480,
    "amount": 45
},
```

### What is the solution
Two options:
- A non breaking change adds a `List<Helldivers.Models.V1.Reward> Rewards` to the `Helldivers.Models.V1.Assignment` in addition to the existing `Reward` property. The `Reward` is deprecated.
- A breaking change replaces the existing `Reward` with a `List<Helldivers.Models.V1.Reward> Rewards`.

### Existing alternatives
Clients use the raw API to get assignment information (see JSON sample above).

### Added value
Clients receive all rewards and can use / display them correctly.

### Additional notes
None.

**Comment by dealloc** [comment]
I feel like in this case the breaking change is the way to go, mainly because it's the way AH does it and we want to maintain similarity between the API's

@chatterchats thoughts?

**Comment by raginmari** [comment]
How would a breaking change be implemented so that existing projects like the "War Monitor" app keep working? Would have be a "v2" of the API, right (I'm doing mobile frontend mostly, so I don't have much experience with API development)?

**Comment by chatterchats** [comment]
> I feel like in this case the breaking change is the way to go, mainly because it's the way AH does it and we want to maintain similarity between the API's
> 
> @chatterchats thoughts?

I mean, I'll be honest, mine is kinda already doing it 👀 but mines a lot simpler than yours and acts more as a relay w/ no data validation (explicitly because AH kept/keeps changing their stuff)
![image](https://github.com/user-attachments/assets/8e752f2d-1ca0-4798-9719-e095f805787a)

**Comment by Stonemercy** [comment]
I too would like this ASAP :)
