### ISSUE TITLE
Overview of all planets in the current war returns `"disabled": false` for all planets.

### ISSUE THREAD

**Issue by MikeODonovan** [helldivers-2/api#15]
When calling `/api/{war_id}/planets` all planets return `"disabled": false`

example:
```json
{
    "disabled": false,
    "hash": 897386910,
    "index": 0,
    "initial_owner": "Humans",
    "max_health": 1000000,
    "name": "Super Earth",
    "position": {
      "x": 0,
      "y": 0
    },
    "sector": "Sol",
    "waypoints": [
      1
    ]
  },
```
Super Earth should be disabled at the moment unless I'm missing something.

I'm fiddling around with creating a bot that displays things like, in this case, the currently active planets. In the meantime, I'll see about using `/api/{war_id}/status` instead. Probably the better option for my uses anyway, but I noticed this and thought I'd mention it.

**Comment by dealloc** [comment]
I've noticed this behaviour as well, unfortunately this field is mapped 1-1 from the underlying API of ArrowHead, either it's unused by them or bugged but we always receive a `false` value.

I recommend using the `status` endpoint for currently active planets for the moment

**Comment by Kejax** [comment]
If I'd guess, then I'd say that it's maybe bound to some other deactivation like GM interface and not the "you can't play here" deactivation

**Comment by chatterchats** [comment]
My guess is the planets aren't disabled in that they are still active within the game. but places like the illuminate homeworld which isn't on the map yet would be disable

**Comment by Kejax** [comment]
That's the kind of deactivated I mean, yeah
