### ISSUE TITLE
Planet Statistics

### ISSUE THREAD

**Issue by sebsebmc** [helldivers-2/api#20]
![image](https://github.com/dealloc/helldivers2-api/assets/2250975/f8680c3b-c273-4b6c-b4e7-924ea58de2f0)

I believe that these APIs in the past were disabled for stability reasons and have now been stably up for a bit. Would be good to find out how to get these values as well.

**Comment by dealloc** [comment]
the first one would theoretically just be a summation of all planet playercounts.
The other numbers are most likely from a not yet known endpoint :/

**Comment by stnokott** [comment]
We have these statistics now under `/api/v1/war`, don't we?

| Statistic | Path |
| ------------- | ------------- |
| Helldivers Active  | `$.statistics.playerCount` |
| Enemies Killed  | `$.statistics.terminidKills + $.statistics.automatonKills + $.statistics.illuminateKills` |
| Helldivers KIA | `$.statistics.deaths` |
| Bullets Fired | `$.statistics.bulletsFired` |

**Comment by sebsebmc** [comment]
Yes and I believe it also returns the statistics per planet in the V1 API as well.
