### ISSUE TITLE
Orders and Events Question

### ISSUE THREAD

**Issue by milogert** [helldivers-2/api#25]
Thanks for the API! A friend and I are working on a site that uses it as a source for data. Do you know how to access the Major Orders and the Personal Orders? It's something we'd really like to include on our site but looking at the api I am not sure where they are.

Additionally, do you know when (if?) the `events` endpoint will be populated? I've been keeping an eye on it for the past few days and it always seems to return an empty array. But I might have missed something.

Thanks again! Also, in my free time I am an Elixir dev, so if you need any help working on this API I'd be happy to pitch in

**Comment by dealloc** [comment]
turns out this was an issue with certain parameters not being passed in.
as far as I can see this is no longer an issue in the V1 API, so I'm going to close this issue for now
