### ISSUE TITLE
Waypoints are supply lines! (Possibly?)

### ISSUE THREAD

**Issue by BoxedFruits** [helldivers-2/api#26]
https://github.com/dealloc/helldivers2-api/blob/45a17d4bef56128be06d3a38ee2624a56f40f294/lib/helldivers_2_web/schemas/planet_schema.ex#L40
    
Was doing some digging and realized that waypoints are supply lines. The array maps to the indexes of the planets it goes to.
So for example "Azur Secundus" has waypoints: [213]. The planet with index 213 is "Overgoe Prime".

I am also going off of https://helldivers.io/ and it matches

Let me know if you agree and I can open a PR to update the docs

**Comment by dealloc** [comment]
Ah yes, we realized that a while back but we didn't get around to updating the documentation but feel free to open a PR!

The reason we don't link them as planets is that it would cause recursive parsing (and a significant increase in memory consumption)

**Comment by BoxedFruits** [comment]
Looks it was update recently, possibly with the v1 release
Love the work that you are all putting in!
