### ISSUE TITLE
Detail not found from /events/latest endpoint when global event is active

### ISSUE THREAD

**Issue by Atreatis** [helldivers-2/api#29]
It seems that the endpoint `/api/{war_id}/events/latest` no longer provides data when an global event is active and returns a `Not Found` error. 

Reproduction:
- Wait till a `Global Event` is active,
- Try and fetch data from the endpoint:  `/api/{war_id}/events/latest`

Results:
```
{"errors":{"detail":"Not Found"}}
```

Expected Results:
- Provide current global event information

**Comment by lambstream** [comment]
I can't seem to be able to reproduce this?

There's a currently active event and the endpoint seems to return the correct information.

I used this endpoint /api/801/events/latest

**Comment by lambstream** [comment]
Could you perhaps provide us with a little more information as to what went wrong?

**Comment by Atreatis** [comment]
Hello there,

Currently just checked on my own endpoint `ForgeDevs` as on the `Helldivers 2 API` one it seems to be confirmed working now on both. This seems to happen shortly after the event has been recently closed or opened, I've noticed this happening by three times now, could it be an option to keep this open for now and see what happens during next few events?

As for refference both links:
```
https://diveapi.forgedevs.com/api/801/events/latest
```

And also seems to be working/present on your own API as well
```
https://helldivers-2.fly.dev/api/801/events/latest
```

**Comment by lambstream** [comment]
Sounds like this could possibly be a syncing issue on our end.

We are current working on a rewrite in .NET and we will take a new look at this once that has been merged to master.

**Comment by dealloc** [comment]
@Atreatis does the issue still persist on the new v1 endpoints?

**Comment by Atreatis** [comment]
> @Atreatis does the issue still persist on the new v1 endpoints?

Will have a look right away, past few weeks been quite wild so I have been out of the loop of everything.

**Comment by Atreatis** [comment]
It has been a while and there's been some changes in my life that required me to stop the development of my personal project and haven't been able to check out if it was resolved.

I do sincerely want to wish best of luck and prosper with your API Project because it is definitely a nice project to have around for other developers that do have more time then I do.

**Comment by dealloc** [comment]
no problem, I'll close this but feel free to open a new issue if something pops up.
Best of luck @Atreatis
