### ISSUE TITLE
Possible to get defense campaign status?

### ISSUE THREAD

**Issue by TheWizardofGauze** [helldivers-2/api#32]
I was wondering if there was a known way to get status of a defense campaign. So far from what I've tried by using 
`https://helldivers-2.fly.dev/api/{war_id}/planets/{planet_index}/status`
The defense planets are showing `"health": 1000000, "liberation": 100`.

Is there different planet information I can get that tells me or is it not known/not possible?

**Comment by xSentry** [comment]
Under `https://helldivers-2.fly.dev/api/801/status` you see the key `planet_events`.
There you can find info on active defense campaigns.
But the dates are currently wrongly formatted.
To get the correct unformatted TimeStamps you have to use `https://api.live.prod.thehelldiversgame.com/api/WarSeason/801/Status`.

But the TimeStamps there are relative to the WarSeason Time (Start of Season in Seconds) so keep that in mind.

**Comment by TheWizardofGauze** [comment]
Ah now I see it, that makes sense. Thank you!
