### ISSUE TITLE
/api/v1/assignments returns null for text without language headers

### ISSUE THREAD

**Issue by weaveul** [helldivers-2/api#33]
Hey,
The api https://helldivers-2-dotnet.fly.dev/api/v1/assignments gives me null when I query it in python for the title, brief and description.
I had to add the headers = {"Accept-Language": "fr-FR"}
to finally have content

**Comment by dealloc** [comment]
seems that `LocalizedMessage` doesn't automatically select the correct languages when none are explicitly passed.
