### ISSUE TITLE
[BUG]: Dispatches endpoint only returning 10 or so items

### ISSUE THREAD

**Issue by chatterchats** [helldivers-2/api#38]
### Link to faulty endpoint

https://helldivers-2-dotnet.fly.dev/api/v1/dispatches

### The name of your client/application

Mozilla FireFox

### Request information

Need to include the maxEntries query param to the url.

### Steps to reproduce

Load https://helldivers-2-dotnet.fly.dev/api/v1/dispatches in a browser.

### What is expected?

Returns all newsfeed items

### What is actually happening?

```json
Only returns the first 10 or so
```

### System Info

```shell
Windows 10
Firefox
```

### Any additional comments?

No

**Comment by TheWizardofGauze** [comment]
It looks like "message" is returning null for each entry as well

**Comment by dealloc** [comment]
message does seem to return messages for me, might've been a temporary outage
![image](https://github.com/helldivers-2/api/assets/2164354/7c22a8f9-3322-4008-9185-7de30ef28ddd)
