### ISSUE TITLE
[BUG]: Wrong links for new deployment.

### ISSUE THREAD

**Issue by chatterchats** [helldivers-2/api#44]
### Link to faulty endpoint

https://github.com/helldivers-2/api

### The name of your client/application

Mozilla FF

### Request information

Just loading github.com/helldivers-2/api

### Steps to reproduce

Clicking on service link or the readme.md's links,
![image](https://github.com/helldivers-2/api/assets/57570001/c36101f7-08e4-4c73-84ab-d7dc329719d0)

### What is expected?

Link to take me to the current function api at -dotnet

### What is actually happening?

```json
getting links to the old api
```

### System Info

```shell
Windows 10
Firefox FF
```

**Comment by lambstream** [comment]
Seeming as we are sunsetting the Elixir application we should update this. Can we get your confirmation @dealloc?

**Comment by dealloc** [comment]
it's been updated
![image](https://github.com/helldivers-2/api/assets/2164354/fed5c07f-c78d-4f29-b33d-04b503524769)
