### ISSUE TITLE
[FEATURE]: Docker Setup

### ISSUE THREAD

**Issue by Stonemercy** [helldivers-2/api#46]
### What problem does it solve
I figured it would help people setup self-hosted version easier :)

### What is the solution
Dockerize!

### Existing alternatives
🤷🏻‍♂️ 

### Added value
Just makes it easier to setup a docker container for self-hosting

### Additional notes
Sorry for this lackluster request, I don't really know what else to add

**Comment by v-boivin** [comment]
The .NET rewrite seems to have removed the docker setup guide

It's available in this previous commit:
https://github.com/helldivers-2/api/tree/ffea9d9f9e7d5acfea3fc8aa814f4340bb48b273

**Comment by stnokott** [comment]
It'll probably be something along the lines of

```bash
# clone the repository (including submodules for static data)
git clone --recurse-submodules https://github.com/helldivers-2/api
# enter the newly cloned directory
cd api
# build the docker image
docker build -f ./src/Helldivers-2-API/Dockerfile -t helldivers2:latest .
```

That should work for building, but I haven't figured out (yet), which URL the new endpoints are under.

**Comment by stnokott** [comment]
Should be something along the lines of:

```bash
# clone Git repo (including subrepos)
git clone --recurse-submodules https://github.com/helldivers-2/api
# enter newly cloned directory
cd api
# build docker image
docker build -f ./src/Helldivers-2-API/Dockerfile -t helldivers2-api .
# run image
docker run -p 8080:8080 helldivers2-api
```

Swagger UI is then accessible under [http://localhost:4000/swagger-ui.html](http://localhost:4000/swagger-ui.html).

E.g. current war status under [http://localhost:4000/api/v1/war](http://localhost:4000/api/v1/war).

**Comment by dealloc** [comment]
the steps provided above are basically how to get the API going.
We're setting up more 'advanced' documentation such as Docker etc in #52 so once that's merged we can get this issue started!

**Comment by dealloc** [comment]
@Stonemercy I added documentation for running containers in d467716
could you get back to me if there's more details you require added?

**Comment by Stonemercy** [comment]
> @Stonemercy I added documentation for running containers in [d467716](https://github.com/helldivers-2/api/commit/d4677163fe430257936715740150f27f7bf169b9) could you get back to me if there's more details you require added?

Looks great!
