### ISSUE TITLE
[BUG]: War factions is empty

### ISSUE THREAD

**Issue by sebsebmc** [helldivers-2/api#47]
### Link to faulty endpoint

/api/v1/war

### The name of your client/application

https://github.com/sebsebmc/helldivers-history

### Request information

Factions currently responds with `[]` and no actual data

### Steps to reproduce

curl -H "Accept-Language: en-us" https://helldivers-2-dotnet.fly.dev/api/v1/war

### What is expected?

Something like `["Humans", "Terminids", "Automatons"]`

### What is actually happening?

```json
{"started":"2024-01-23T20:05:13Z","ended":"2028-02-08T20:04:55Z","now":"1970-02-24T10:33:40Z","clientVersion":"0.3.0","factions":[],"impactMultiplier":0.012120398,"statistics":{"missionsWon":112362781,"missionsLost":11913252,"missionTime":119763643969,"terminidKills":9386109258,"automatonKills":3204924753,"illuminateKills":28,"bulletsFired":82143992697,"bulletsHit":83056767905,"timePlayed":119763643969,"deaths":407118779,"revives":2,"friendlies":56219002,"missionSuccessRate":90,"accuracy":100,"playerCount":245023}}
```
```


### System Info

_No response_

### Any additional comments?

_No response_

**Comment by lambstream** [comment]
Thanks for the detailed issue.

Should be fixed in [this](https://github.com/helldivers-2/api/pull/49) PR.
