### ISSUE TITLE
[BUG]: Assignment title not displaying correctly

### ISSUE THREAD

**Issue by TheWizardofGauze** [helldivers-2/api#53]
### Link to faulty endpoint

https://helldivers-2-dotnet.fly.dev/api/v1/assignments

### The name of your client/application

python-requests/2.31.0

### Request information

aresponse = requests.get("https://helldivers-2-dotnet.fly.dev/api/v1/assignments")

### Steps to reproduce

Visit the assignments endpoint.

### What is expected?

Title should be actual words relevant to the content of the assignment.

### What is actually happening?

```json
Title instead has a value of "#A / <i=1>#B</i>".
```

### System Info

```shell
Python, VSCode, Chrome 123.0.6312.106
```

### Any additional comments?

Unsure if this is an issue with the Arrowhead endpoint or this API's endpoint.

**Comment by xSentry** [comment]
This is not a bug.
The official Title that is comming from the ArrowHead API displays the exact same value.
Since we can just work with the values ArrowHead is providing, there isnt really a workaround for that, since the data is already comming "bugged" from the official endpoints.

Screenshot from the official return data:
![grafik](https://github.com/helldivers-2/api/assets/45976427/0dec4234-10b5-4500-8fec-c11e9414d7b6)

**Comment by TheWizardofGauze** [comment]
Fair enough, figured I might as well bring it up just in case. Thanks.

**Comment by dloy4k** [comment]
> Fair enough, figured I might as well bring it up just in case. Thanks.

I resolved this (in my code) with the following: (tweak as needed)
```python
            url = f"https://helldivers-2-dotnet.fly.dev/api/v1/dispatches"
            response = requests.get(url)

            if response.status_code == 200:
                data = response.json()
                message = data[0]['message']
                formatted_message = message.replace("<i=3>", "").replace("</i>", "").strip()
                print(formatted_message)
```

**Comment by dealloc** [comment]
I'm not opposed to the argument that in the v1 API (which is a convenience layer anyway) the texts from ArrowHead should be parsed in 'proper' HTML (so the `<i=3>` stuff should be things like `<i>` etc

@TheWizardofGauze if you'd like to turn this into a feature request feel free to open one for that

**Comment by TheWizardofGauze** [comment]
@dealloc sure I can open one when I'm off work unless someone beats me to it
