### ISSUE TITLE
[FEATURE]: Add expiresIn to assignments

### ISSUE THREAD

**Issue by sreece52** [helldivers-2/api#59]
### What problem does it solve
This will allow consumers of the api to obtain the number of seconds until the major order expires in.

### What is the solution
Map the property to the assignment endpoint(s): ```/api/v1/assignments``` and ```/api/v1/assignments/:index```

### Existing alternatives
Making an additional request to the ```/raw/api/v2/Assignment/War/801``` endpoint.

### Added value
Enable consumers of the api to make fewer requests. Improved QOL for api consumers.

### Additional notes
None

**Comment by dealloc** [comment]
looks good, feel free to get a PR started!
