### ISSUE TITLE
[FEATURE]: Add Progress for MO's to v1/assignments

### ISSUE THREAD

**Issue by Stonemercy** [helldivers-2/api#60]
### What problem does it solve
This will allow users to obtain the MO progress for MO's that don't provide specific planets to liberate (in the case of the current MO).

### What is the solution
Map the property to the assignment endpoint(s): `/api/v1/assignments` and `/api/v1/assignments/:index`

### Existing alternatives
Making an additional request to the `/raw/api/v2/Assignment/War/801` endpoint.

### Added value
Lets users make fewer requests for useful info.

### Additional notes
None

**Comment by lambstream** [comment]
Looks good, I'm going to take a look at making a PR for this.
