### ISSUE TITLE
[FEATURE]: Option to fetch all dispatches/assignments in all languages

### ISSUE THREAD

**Issue by sebsebmc** [helldivers-2/api#67]
### What problem does it solve
The old API responded with `global_events` containing the message in all fetchable languages like so (messages truncated for brevity):
```json
"message": {
        "es": "...",
        "fr": "....",
        "de": "....",
        "en": "...",
        "it": "...",
        "pl": "...",
        "ru": "...",
        "zh": "..."
      },
```

### What is the solution
Allow some method of retrieving all versions of the translated strings for dispatches and/or assignments without having to request every single language separately. I would be fine with a separate GET parameter or some specific Accept-Language header.

### Existing alternatives
Making 8+ requests just to have the assignments in each language is annoying and would use up a lot of rate limit.

### Added value
My app currently provides a language picker and ships the messages in all languages so you can choose to see them in any language.

**Comment by lambstream** [comment]
This is a tricky one, I'm going to take a look at our options.

Biggest problem is mapping this change to the Open API documentation because currently the responses can only be strings.

**Comment by lambstream** [comment]
Got the documentation fixed.
Actually generating the different responses is going to be difficult.
We would have to change the JsonConverter options on runtime.

Maybe @dealloc can share his thoughts

**Comment by sebsebmc** [comment]
I myself am struggling to come up with a reasonable solution to this that would not require a separate endpoint and associated types.

**Comment by dealloc** [comment]
just to have all the pieces laid out here in one convenient spot if someone wants to try tackling this:
- [`LocalizedMessage`](https://github.com/helldivers-2/api/blob/f2992c626725a3bef26831cd07bc624704febc2b/src/Helldivers-2-Models/Domain/Localization/LocalizedMessage.cs) is in essence a thin wrapper around a `Dictionary<CultureInfo, string>` that contains all translations of a message it represents
- when serializing to JSON the [`LocalizedMessageConverter`](https://github.com/helldivers-2/api/blob/f2992c626725a3bef26831cd07bc624704febc2b/src/Helldivers-2-Models/Domain/Localization/LocalizedMessageConverter.cs) automatically selects the language (from `CultureInfo.CurrentCulture`, which is automatically set by the request localization middleware to the `CultureInfo` the client requests with `Accept-Language` header.

There's 2 difficult problems to solve:
1. The OpenAPI specification generated needs to indicate that it can return both `string` or `{"<lang>": "<message>"}` when something is typed as a `LocalizedMessage`
2. Somehow the `LocalizedMessageConverter` would need to know to serialize something as either a string (for a specific locale) or as a dictionary of all languages

I'm fairly certain @lambstream already managed to solve `1`, however point `2` remains a tricky one.

**Comment by dealloc** [comment]
note to myself, perhaps [FeatureManagement](https://github.com/microsoft/FeatureManagement-Dotnet) is an interesting one for this?

**Comment by lambstream** [comment]
The "easiest" way to fix this IMHO would be to make a separate env that turns off the LocalizedMessageConverter. 
The caveat is that we would have to run and maintain 2 instances of the API.

**Comment by sebsebmc** [comment]
What about a doing something like `api/v1/dispatches/multilang` and `api/v1/assignments/multilang`?

**Comment by dealloc** [comment]
Wouldn't solve the serialisation issue

**Comment by sebsebmc** [comment]
Sure, just trying to avoid you needing to change the API types
