### ISSUE TITLE
[BUG]: Public SwaggerUI unavailable due to CORS

### ISSUE THREAD

**Issue by stnokott** [helldivers-2/api#71]
### Link to faulty endpoint

https://helldivers-2.github.io/api/docs/openapi/swagger-ui.html

### The name of your client/application

n/a

### Request information

Querying the public GitHub pages [SwaggerUI](https://helldivers-2.github.io/api/docs/openapi/swagger-ui.html) as linked in the README after #68 results in an empty page.

The reason for this is that the `swagger-ui-bundle.js` library doesn't load due to CORS policy.

Console log in browser:
`Access to script at 'https://unpkg.com/swagger-ui-dist@5.11.0/swagger-ui-bundle.js' from origin 'https://helldivers-2.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

### Steps to reproduce

1. Open public [SwaggerUI](https://helldivers-2.github.io/api/docs/openapi/swagger-ui.html)

### What is expected?

SwaggerUI is expected to load.

### What is actually happening?

```json
CORS policy prevents the SwaggerUI JS library from loading.
```

### System Info

```shell
n/a
```

### Any additional comments?

No prior experience with GitHub pages, so unfortunately I can't help with this topic.

**Comment by dealloc** [comment]
odd, I can't seem to reproduce this one?

I'm running Firefox on Windows 11 and I can open the SwaggerUI just fine
![image](https://github.com/helldivers-2/api/assets/2164354/b52548d9-c643-4a65-a99f-8522bd704235)

What browser/OS are you running?

**EDIT** I tested with Microsoft Edge as well (as that's one I also had installed) and it opened just fine there as well

**Comment by stnokott** [comment]
I also have Firefox on Windows 11...

![image](https://github.com/helldivers-2/api/assets/30934296/b937d9fd-a3c7-4e8d-a7aa-91d2aac7bef6)

Feel free to close the issue though, seems to be a client-side issue.

**Comment by stnokott** [comment]
Closing since it's not an issue related to this repo.
