### ISSUE TITLE
[BUG]: github.io not redirecting to OpenAPI properly

### ISSUE THREAD

**Issue by TheWizardofGauze** [helldivers-2/api#76]
### Link to faulty endpoint

https://helldivers-2.github.io/api/

### The name of your client/application

N/A

### Request information

N/A

### Steps to reproduce

- Visit https://helldivers-2.github.io/api/
- Click on "OpenAPI"

### What is expected?

It should redirect to https://helldivers-2.github.io/api/docs/openapi/swagger-ui.html

### What is actually happening?

```json
It currently redirects to https://helldivers-2.github.io/docs/openapi/swagger-ui.html resulting in a 404 page.
```

### System Info

```shell
Chrome 123.0.6312.123
```

**Comment by dealloc** [comment]
oops! Good catch
