### ISSUE TITLE
[BUG]: Dispatches have incorrect publishing date

### ISSUE THREAD

**Issue by chris-kaiser-7** [helldivers-2/api#78]
### Link to faulty endpoint

https://helldivers-2-dotnet.fly.dev/api/v1/dispatches

### The name of your client/application

curl / browser

### Request information
```shell
curl 'https://helldivers-2-dotnet.fly.dev/api/v1/dispatches' \
  -H 'authority: helldivers-2-dotnet.fly.dev' \
  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'cache-control: max-age=0' \
  -H 'sec-ch-ua: "Chromium";v="122", "Not(A:Brand";v="24", "Google Chrome";v="122"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'sec-fetch-dest: document' \
  -H 'sec-fetch-mode: navigate' \
  -H 'sec-fetch-site: none' \
  -H 'sec-fetch-user: ?1' \
  -H 'upgrade-insecure-requests: 1' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'
```

### Steps to reproduce

Make a get request to "https://helldivers-2-dotnet.fly.dev/api/v1/dispatches" 

### What is expected?

published fields in dispatches endpoint reflect the date the dispatch occurred. 

### What is actually happening?

When making a GET request to "https://helldivers-2-dotnet.fly.dev/api/v1/dispatches" the published fields timestamp seem to be around 18 days behind the actually value. For example the dispatch that was posted today on 4/18/2024 has the value {"published": "2024-03-31T22:49:13Z"} when it should have a value close to "2024-04-18T05:20:03Z".

**Comment by dealloc** [comment]
fairly certain this will be related to #21
appreciate the writeup, this will definitely help finding a fix for this!

@lambstream you up to tackle this one?
