### ISSUE TITLE
[BUG]: Possible Resource leak

### ISSUE THREAD

**Issue by Stonemercy** [helldivers-2/api#83]
### Link to faulty endpoint

N/A

### The name of your client/application

Self-Hosted API

### Request information

CPU and RAM usage seem to be increasing over time (up to 50% CPU and 500MB RAM after around 2 weeks)

![image](https://github.com/helldivers-2/api/assets/3813858/d1e2419e-d71a-47fe-b5b5-d727449ff5a3)
^ on startup
![image](https://github.com/helldivers-2/api/assets/3813858/2148fe32-ace9-40d0-9a56-3de65824ba60)
^after 24 hours

![image](https://github.com/helldivers-2/api/assets/3813858/745c2f70-94c9-419f-9439-081222b136c1)
^ on startup
![image](https://github.com/helldivers-2/api/assets/3813858/c428b8fa-08ed-466e-8878-f0edacf6303c)
^ after 24 hours

### Steps to reproduce

1. RUN API
2. ?????
3. Usage goes up

I'm not 100% on the process of setting it up 

### What is expected?

CPU and RAM levels to stay stable

### What is actually happening?

```json
CPU and RAM usage increases over time (CPU seemingly capped at around 50%)
```

### System Info

```shell
RAM: 8GB
CPU: AMD EPYC-Milan Processor (2C\4T) (as much info as we can get)
```

### Any additional comments?

Since this is an old version of the API (still V1) we'll update it before proceeding.

**Comment by dealloc** [comment]
I kept the API running for about a day and it didn't increase too much.
So it's probably not related to the synchronization but the API responding to endpoint requests.

This narrows it down

**Comment by stnokott** [comment]
I have the API running as a Docker container, with another container requesting almost every endpoint sequentially, every 10mins.

Resource usage of both containers is stable.
If required for further investigation, I could reduce the time between sequential API requests...?

**Comment by dealloc** [comment]
I've profiled the application but memory usage didn't increase beyond reasonable growth (aka hitting the endpoint with 100 concurrent users creates more memory, but that's because it's servicing a higher load).

@Stonemercy did mention he's running an older build, perhaps the issue was already resolved with one of the later updates?

**Comment by Stonemercy** [comment]
After running an updated version of the API for 2 days and having it idle at basically 1%, I think it's safe to assume it was an issue with the previous version we were running on which has since been fixed. 

Happy to close this unless you want to investigate more 👍🏻

**Comment by dealloc** [comment]
I'll close this, but should we run into resource leaks in the future feel free top open a new bug :)
