### ISSUE TITLE
[BUG]: Inconsistent data type for Campaign IDs (int32/int64)

### ISSUE THREAD

**Issue by stnokott** [helldivers-2/api#85]
### Link to faulty endpoint

https://helldivers-2.github.io/

### The name of your client/application

n/a

### Request information

n/a

### Steps to reproduce

1. Open official [SwaggerUI](https://helldivers-2.github.io/api/docs/openapi/swagger-ui.html)
2. Check data type of `Campaign.Id` (raw type) -> `$int32`
3. Check data type of `Campaign2.Id` (parsed type) -> `$int32`
4. Check data type of `Event.campaignId` -> `$int64`

### What is expected?

Campaign IDs across all endpoints should be of equal type.

### What is actually happening?

Campaign ID types from `/raw/api/WarSeason/801/Status` and `/api/v1/campaigns` match (both `int32`), but the type from `/api/v1/planet-events` (`int64`) falls out of line.

### System Info

```shell
n/a
```

### Any additional comments?

I am pretty confident that the game will never reach a point where the campaign IDs will exceed the limits of `int32`, so it should be safe to use `int32` for client applications.

Still, this is an inconsistency in the OpenAPI schema and should be fixed.

**Comment by dealloc** [comment]
good catch!
