### ISSUE TITLE
[FEATURE]: /docs/ route for swagger documentation

### ISSUE THREAD

**Issue by chatterchats** [helldivers-2/api#88]
### What problem does it solve
With only the API link of [helldivers2.dev](https://api.helldivers2.dev) as a reference, any potential users not aware of the GitHub and the links to the swagger documentation would have a hard time figuring out the end point locations

### What is the solution
Add the standardized /docs/ route that is either sends a 307 Redirect to the [SwaggerUI](https://helldivers-2.github.io/api/docs/openapi/swagger-ui.html) or have the route return the webpage itself.

### Existing alternatives
The only alternative existing is located at https://helldivers-2.github.io/api/docs/openapi/swagger-ui.html - A link detached from the actual end point provider.

### Added value
This would allow lay-users of the API easier access to the documentation, allowing them to successfully utilize this service.

### Additional notes
[.NET Documentation on HTTPResponse.Redirect](https://learn.microsoft.com/en-us/dotnet/api/system.web.httpresponse.redirect?view=netframework-4.8.1)

**Comment by lambstream** [comment]
This would also be a good time to remove the development server from the "Try it out" section of the swagger...

**Comment by dealloc** [comment]
Alternatively, instead of the docs we could have a response on the `/` endpoint?

If you open the root link it gives you a small text where to find docs etc?
Similar to the diveharder API

**Comment by chatterchats** [comment]
> Alternatively, instead of the docs we could have a response on the `/` endpoint?
> 
> If you open the root link it gives you a small text where to find docs etc? Similar to the diveharder API

That could work as well
