### ISSUE TITLE
[FEATURE]: make `X-Super-Client` header required

### ISSUE THREAD

**Issue by dealloc** [helldivers-2/api#94]
### What problem does it solve
It requires clients using the hosted version of the API to send along a `X-Super-Client` header that identifies their application, and optionally a `X-Super-Contact` header with developer contact info.

This allows us to identify applications and contact developers when implementing breaking changes or if their apps are causing problems.

### What is the solution
Make the header required (after a grace period)

### Existing alternatives
none

### Added value
This allows us to identify applications and contact developers when implementing breaking changes or if their apps are causing problems.

### Additional notes
Provide a way to disable this check for self-hosted containers

**Comment by chatterchats** [comment]
What kind of grace period are we looking at for mandatory implementation?

**Comment by dealloc** [comment]
mostly depends on how fast I can identify most developers and communicate the changes

We left the Elixir version up and running for approximately 30-50 days

**Comment by chatterchats** [comment]
HellCom Support PR [#11](https://github.com/helldivers-2/discord-bot/pull/11)
