### ISSUE TITLE
[BUG]: L'estrade sector name typo

### ISSUE THREAD

**Issue by paulleonartcalvo** [helldivers-2/api#98]
### Link to faulty endpoint

https://api.helldivers2.dev/api/v1/planets/259

### The name of your client/application

Helldiver Strategos

### Request information

Planet name is just wrong. At least according to game client should be "L'estrade"

### Steps to reproduce

Run query, check body for `sector` for planet **Omicron**

### What is expected?

should be "L'estrade"

![image](https://github.com/helldivers-2/api/assets/93534747/a0c6407d-7b0a-4050-a6ea-c232ad368b6a)

### What is actually happening?

```json
It is showing "Le'strade"
```

**Comment by paulleonartcalvo** [comment]
This seems like it's a them thing

**Comment by paulleonartcalvo** [comment]
Looks like these are defined here:

https://github.com/helldivers-2/json/blob/master/planets/planets.json

**Comment by dealloc** [comment]
linked in helldivers-2/json#33
